name: becadmin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_auth: ^3.3.16
  firebase_core: ^1.15.0
  cloud_firestore: ^3.1.13
  firebase_storage: ^10.2.14
  google_sign_in: ^5.3.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  get: ^4.6.1
  http: ^0.13.4

  flutter_staggered_grid_view: ^0.6.1
  
  flutter_phone_direct_caller: ^2.1.1
  flutter_email_sender: ^5.1.0
  url_launcher: ^6.0.20

  file_picker: ^4.6.1
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700