
//Sem and Subject Data
Map<String, dynamic> departments = {
  'Civil Engineering': {
    'p - cycle': [
      'physics',
      'electrical',
      'cpp',
      'environment',
    ],
    'c - cycle': [
      'mechanics',
      'cad',
      'chemistry',
      'electronics',
    ],
    '3 - semester': [
      'mom',
      'concrete',
      'buildingmaterial',
      'geology',
      'surveying',
    ],
    '4 - semester': [
      'sur',
      'sa',
      'he',
      'fm',
      'ct',
    ],
    '5 - semester': [
      'gte',
      'structure',
      'management',
      'hydrolics',
      'geotech',
    ],
    '6 - semester': [
      'abmt',
      'rc',
      'geotech',
      'hydrology',
    ],
    '7 - semester': [
      'is',
      'pscs',
      'steel',
      'environment',
    ],
    '8 - semester': [
      'cm',
    ],
  },
  'Computer Science': {
    'p - cycle': [
      'physics',
      'electrical',
      'cpp',
      'environment',
    ],
    'c - cycle': [
      'mechanics',
      'cad',
      'chemistry',
      'electronics',
    ],
    '3 - semester': [
      'sdfdds',
      'sdfsdf',
      'dsfqsd',
      'khjj',
      'dfdsaa',
    ],
    '4 - semester': [
      'sur',
      'dgdffdgdf',
      'hdfgdfgdfgdfe',
      'ffdgdffgdm',
      'cdfgdt',
    ],
    '5 - semester': [
      'gte',
      'structure',
      'management',
      'hydrolics',
      'geotech',
    ],
    '6 - semester': [
      'abmt',
      'rc',
      'geotech',
      'hydrology',
    ],
    '7 - semester': [
      'is',
      'pscs',
      'steel',
      'environment',
    ],
    '8 - semester': [
      'cm',
    ],
  },
  'Artificial Intelligence': {
    'p - cycle': [
      'physics',
      'electrical',
      'cpp',
      'environment',
    ],
    'c - cycle': [
      'mechanics',
      'cad',
      'chemistry',
      'electronics',
    ],
    '3 - semester': [
      'sdfdds',
      'sdfsdf',
      'dsfqsd',
      'khjj',
      'dfdsaa',
    ],
    '4 - semester': [
      'sur',
      'dgdffdgdf',
      'hdfgdfgdfgdfe',
      'ffdgdffgdm',
      'cdfgdt',
    ],
    '5 - semester': [
      'gte',
      'structure',
      'management',
      'hydrolics',
      'geotech',
    ],
    '6 - semester': [
      'abmt',
      'rc',
      'geotech',
      'hydrology',
    ],
    '7 - semester': [
      'is',
      'pscs',
      'steel',
      'environment',
    ],
    '8 - semester': [
      'cm',
    ],
  },
  'Bio technology': {
    'p - cycle': [
      'physics',
      'electrical',
      'cpp',
      'environment',
    ],
    'c - cycle': [
      'mechanics',
      'cad',
      'chemistry',
      'electronics',
    ],
    '3 - semester': [
      'sdfdds',
      'sdfsdf',
      'dsfqsd',
      'khjj',
      'dfdsaa',
    ],
    '4 - semester': [
      'sur',
      'dgdffdgdf',
      'hdfgdfgdfgdfe',
      'ffdgdffgdm',
      'cdfgdt',
    ],
    '5 - semester': [
      'gte',
      'structure',
      'management',
      'hydrolics',
      'geotech',
    ],
    '6 - semester': [
      'abmt',
      'rc',
      'geotech',
      'hydrology',
    ],
    '7 - semester': [
      'is',
      'pscs',
      'steel',
      'environment',
    ],
    '8 - semester': [
      'cm',
    ],
  },
  'Electronics and Communication': {
    'p - cycle': [
      'physics',
      'electrical',
      'cpp',
      'environment',
    ],
    'c - cycle': [
      'mechanics',
      'cad',
      'chemistry',
      'electronics',
    ],
    '3 - semester': [
      'sdfdds',
      'sdfsdf',
      'dsfqsd',
      'khjj',
      'dfdsaa',
    ],
    '4 - semester': [
      'sur',
      'dgdffdgdf',
      'hdfgdfgdfgdfe',
      'ffdgdffgdm',
      'cdfgdt',
    ],
    '5 - semester': [
      'gte',
      'structure',
      'management',
      'hydrolics',
      'geotech',
    ],
    '6 - semester': [
      'abmt',
      'rc',
      'geotech',
      'hydrology',
    ],
    '7 - semester': [
      'is',
      'pscs',
      'steel',
      'environment',
    ],
    '8 - semester': [
      'cm',
    ],
  },
  'Electronics and Electricals': {
    'p - cycle': [
      'physics',
      'electrical',
      'cpp',
      'environment',
    ],
    'c - cycle': [
      'mechanics',
      'cad',
      'chemistry',
      'electronics',
    ],
    '3 - semester': [
      'sdfdds',
      'sdfsdf',
      'dsfqsd',
      'khjj',
      'dfdsaa',
    ],
    '4 - semester': [
      'sur',
      'dgdffdgdf',
      'hdfgdfgdfgdfe',
      'ffdgdffgdm',
      'cdfgdt',
    ],
    '5 - semester': [
      'gte',
      'structure',
      'management',
      'hydrolics',
      'geotech',
    ],
    '6 - semester': [
      'abmt',
      'rc',
      'geotech',
      'hydrology',
    ],
    '7 - semester': [
      'is',
      'pscs',
      'steel',
      'environment',
    ],
    '8 - semester': [
      'cm',
    ],
  },
  'Electronics and Instrumentation': {
    'p - cycle': [
      'physics',
      'electrical',
      'cpp',
      'environment',
    ],
    'c - cycle': [
      'mechanics',
      'cad',
      'chemistry',
      'electronics',
    ],
    '3 - semester': [
      'sdfdds',
      'sdfsdf',
      'dsfqsd',
      'khjj',
      'dfdsaa',
    ],
    '4 - semester': [
      'sur',
      'dgdffdgdf',
      'hdfgdfgdfgdfe',
      'ffdgdffgdm',
      'cdfgdt',
    ],
    '5 - semester': [
      'gte',
      'structure',
      'management',
      'hydrolics',
      'geotech',
    ],
    '6 - semester': [
      'abmt',
      'rc',
      'geotech',
      'hydrology',
    ],
    '7 - semester': [
      'is',
      'pscs',
      'steel',
      'environment',
    ],
    '8 - semester': [
      'cm',
    ],
  },
  'Industrial Production': {
    'p - cycle': [
      'physics',
      'electrical',
      'cpp',
      'environment',
    ],
    'c - cycle': [
      'mechanics',
      'cad',
      'chemistry',
      'electronics',
    ],
    '3 - semester': [
      'sdfdds',
      'sdfsdf',
      'dsfqsd',
      'khjj',
      'dfdsaa',
    ],
    '4 - semester': [
      'sur',
      'dgdffdgdf',
      'hdfgdfgdfgdfe',
      'ffdgdffgdm',
      'cdfgdt',
    ],
    '5 - semester': [
      'gte',
      'structure',
      'management',
      'hydrolics',
      'geotech',
    ],
    '6 - semester': [
      'abmt',
      'rc',
      'geotech',
      'hydrology',
    ],
    '7 - semester': [
      'is',
      'pscs',
      'steel',
      'environment',
    ],
    '8 - semester': [
      'cm',
    ],
  },
  'Information Science': {
    'p - cycle': [
      'physics',
      'electrical',
      'cpp',
      'environment',
    ],
    'c - cycle': [
      'mechanics',
      'cad',
      'chemistry',
      'electronics',
    ],
    '3 - semester': [
      'sdfdds',
      'sdfsdf',
      'dsfqsd',
      'khjj',
      'dfdsaa',
    ],
    '4 - semester': [
      'sur',
      'dgdffdgdf',
      'hdfgdfgdfgdfe',
      'ffdgdffgdm',
      'cdfgdt',
    ],
    '5 - semester': [
      'gte',
      'structure',
      'management',
      'hydrolics',
      'geotech',
    ],
    '6 - semester': [
      'abmt',
      'rc',
      'geotech',
      'hydrology',
    ],
    '7 - semester': [
      'is',
      'pscs',
      'steel',
      'environment',
    ],
    '8 - semester': [
      'cm',
    ],
  },
  'Mechanical Engineering': {
    'p - cycle': [
      'physics',
      'electrical',
      'cpp',
      'environment',
    ],
    'c - cycle': [
      'mechanics',
      'cad',
      'chemistry',
      'electronics',
    ],
    '3 - semester': [
      'sdfdds',
      'sdfsdf',
      'dsfqsd',
      'khjj',
      'dfdsaa',
    ],
    '4 - semester': [
      'sur',
      'dgdffdgdf',
      'hdfgdfgdfgdfe',
      'ffdgdffgdm',
      'cdfgdt',
    ],
    '5 - semester': [
      'gte',
      'structure',
      'management',
      'hydrolics',
      'geotech',
    ],
    '6 - semester': [
      'abmt',
      'rc',
      'geotech',
      'hydrology',
    ],
    '7 - semester': [
      'is',
      'pscs',
      'steel',
      'environment',
    ],
    '8 - semester': [
      'cm',
    ],
  },
};




